### ISSUE TITLE
Needs a better solution to  " --enable-ipv6"

### ISSUE THREAD

**Issue by andybe** [kubernetes-sigs/ip-masq-agent#86]
Why isn't there a flag in the configmap  or when ipv6 is detected not enabled ??

```
apiVersion: v1
data:
  config: |
    masqLinkLocal: false
    masqLinkLocalIPv6: true
    enableIPv6 : true  <--- Missing some kind of that
    resyncInterval: 5s
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
```
  
Need  always to change daemonset manual by add:
```
      - args:
        - --masq-chain=IP-MASQ
        - --enable-ipv6
```

Everywhere I'm look around the repos is cloned to add this arguments.

The other way of patch in is a different solution.
